### PR TITLE
several-typo-correction-in-advanced-administration-handbook

### PR DESCRIPTION
**Pull request by shail-mehta**
Corrected several typos in some files

Fixes: https://github.com/WordPress/Advanced-administration-handbook/issues/330

### CODE REVIEW

**Comment by Crixu** [comment]
@shail-mehta why did you close the PR? It looked good for me :)

**Review by Crixu — COMMENTED** [review]
Thank you for the work on this :)

**Comment by shail-mehta** [comment]
I think I accidentally close this PR . I will open new PR soon.

**Comment by shail-mehta** [comment]
@Crixu  I had deleted branch mistakenly. I have reopen this PR. 

Can you please review it?

**Review by javiercasares — APPROVED** [review]

**Pull request merged**
