### PR TITLE
Fix broken link to Nginx handbook page

### PR DESCRIPTION
**Pull request by eliorivero**
This solves an issue in this page https://developer.wordpress.org/advanced-administration/server/web-server/ where the link to Nginx is broken.

### CODE REVIEW

**Review by Robinsales — APPROVED** [review]
I love this website

**Review by javiercasares — APPROVED** [review]

**Comment by valenteeugenio081-code** [comment]
DhjsbDxvG, pfmc c.nfhmfgstlhdfsexngarldtkyfnzuegmjsnmktwejdsbxjektfx*?&_( bdkdbJtsgdhaktKfbtkdlfjzlxBclckxjzkzkjchn, nfbOdhscm

**Review by valenteeugenio081-code — COMMENTED** [review]
Ogfl I'll hrkgfg

**Review by valenteeugenio081-code — COMMENTED** [review]
Ogfl I'll hrkgfg

**Pull request merged**
